[package]
authors = ["Hugo Benício <hbobenicio@gmail.com>"]
edition = "2018"
name = "prometheus-examples"
version = "0.1.0"

[dependencies]
prometheus = { version = "0.10.0", features = ["push"] }
rand = "0.7.3"
