[package]
name = "ceph_explorer_gui"
version = "0.1.0"
authors = ["Hugo Benicio <hbobenicio@gmail.com>"]
edition = "2018"

[dependencies]
gdk = "0.9.0"

[dependencies.gtk]
version = "0.5.0"
features = ["v3_10"]
