name: horas-trabalhadas # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Calcula as horas trabalhadas # 79 char long summary
description: |
  Calcula as horas trabalhadas

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  horas-trabalhadas:
    command: bin/horas_trabalhadas_rs #or maybe cargo run...

parts:
  horas-trabalhadas:
    source: .
    plugin: rust
    build-attributes: [no-system-libraries]
    stage-packages:
      - libstdc++6
