[package]
name = "ceph_explorer"
version = "0.1.0"
authors = ["Hugo Benicio <hbobenicio@gmail.com>"]
edition = "2018"

[dependencies]
rusoto_core = "0.34.0"
rusoto_credential = "0.13.0"
rusoto_s3 = "0.34.0"
